### PR TITLE
In binary.py, moved the calculation of required number of digits to fit

### PR DESCRIPTION
**Pull request by andrethrill**
This is an initial very barebones solution to #34

### CODE REVIEW

**Comment by wdm0006** [comment]
Thanks @andrethrill, I'm on vacation this week but will take a look at this next week.

**Comment by wdm0006** [comment]
Hey @andrethrill sorry for the delay. This PR looks good to me, but the tests are failing. At least the error that's showing up is from master, I've pushed a fix there. Could you pull in the changes from master so travis can re-run tests here and make sure it all checks out?

Thanks, -Will

**Comment by andrethrill** [comment]
Hi @wdm0006 no problem! Everything should be working now

**Comment by wdm0006** [comment]
Awesome, thanks!

**Pull request merged**
