### PR TITLE
Fix tests with new col na categorical

### PR DESCRIPTION
**Pull request by datarian**
Reverting commits and creating branches for #169, #170, #171 and #172 messed up code a bit.
This PR fixes these issues. All unit tests pass again.

Sorry for the mess, will work more carefully in the future

### CODE REVIEW

**Comment by datarian** [comment]
Apparently there is a problem setting up the environment in travis now. As I have zero experience with travis, I would be grateful for help on this.

**Comment by janmotl** [comment]
The first issue that I see:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - scikit-learn 0.20.2* -> python >=3.7,<3.8.0a0
Use "conda info <package>" to see the dependencies for each package.
```
I think we have to bump the version of Python from 3.5 to 3.7.

Also in Python 2.7 run:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.1*
  - scikit-learn 0.20.2* -> mkl >=2019.1,<2020.0a0
  - scikit-learn 0.20.2* -> numpy >=1.11.3,<2.0a0 -> openblas 0.2.19
Use "conda info <package>" to see the dependencies for each package.
```
Suggests that we have to bump the the Numpy version from 1.11.1 to 1.11.3.

Generally, after fixing the first set of errors, new errors appear -> it is an iterative process.

To see the dependencies, I use: https://anaconda.org/anaconda/repo

**Comment by janmotl** [comment]
My proposal for python 3.7:
Downgrade python 3.7 -> python 3.6. Cython 0.25.2 will then work.

For both python2 and python3:
Downgrade scikit-learn 0.20.2 -> 0.20.0, the minimal version that supports ColumnTransformers.

**Comment by datarian** [comment]
Okay, let's see if it passes...

**Comment by datarian** [comment]
Okay, looks like we're homed in now.

**Comment by janmotl** [comment]
Good work.

**Pull request merged**
